### ISSUE TITLE
iphoneXR/11下滑时浏览器底部工具栏隐藏，购物车页面tabbar被遮挡

### ISSUE THREAD

**Issue by Phoebe0626** [Geek-James/ddBuy#78]
iphoneXR/11（带底部黑条的手机）下滑时浏览器底部工具栏隐藏，购物车页面的底部tabbar会被submitbar遮挡。

我的解决方法：给 submitbar 也添加 `safe-area-inset-bottom` 属性，同时设置
```css
/deep/.van-submit-bar {
  bottom: 1.333rem;
  background-color: transparent;
  .van-submit-bar__bar {
    background-color: #fff;
  }
}
```
